'use client'

import { useMemo, useState } from 'react'
import { Activity, ArrowDownRight, ArrowUpRight, Bell, ChevronDown, Clock3, Download, GripVertical, Info, LayoutGrid, Pause, Play, Plus, RefreshCw, Search, Settings2, SlidersHorizontal, Zap } from 'lucide-react'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip as RechartsTooltip, XAxis, YAxis } from 'recharts'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { ChartContainer, ChartTooltipContent } from '@/components/ui/chart'
import { Separator } from '@/components/ui/separator'
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip'

const flow = [{ time: '09:15', value: 1.8, buys: 1.1 }, { time: '09:30', value: 2.5, buys: 1.4 }, { time: '09:45', value: 2.1, buys: 1.8 }, { time: '10:00', value: 3.4, buys: 2.2 }, { time: '10:15', value: 3.1, buys: 2.6 }, { time: '10:30', value: 4.2, buys: 3.0 }, { time: '10:45', value: 3.8, buys: 2.8 }, { time: '11:00', value: 5.1, buys: 3.7 }, { time: '11:15', value: 4.7, buys: 3.4 }, { time: '11:30', value: 6.2, buys: 4.4 }]
const latency = [{ name: '09:15', p50: 18, p95: 35 }, { name: '09:30', p50: 22, p95: 42 }, { name: '09:45', p50: 19, p95: 31 }, { name: '10:00', p50: 28, p95: 51 }, { name: '10:15', p50: 24, p95: 45 }, { name: '10:30', p50: 20, p95: 37 }, { name: '10:45', p50: 21, p95: 40 }, { name: '11:00', p50: 17, p95: 29 }, { name: '11:15', p50: 16, p95: 28 }, { name: '11:30', p50: 14, p95: 25 }]
const symbols = ['ALL', 'TCS', 'HDFCBANK', 'INFY', 'ICICIBANK', 'SBIN', 'TATAMOTORS', 'BHARTIARTL', 'ITC', 'LT', 'RELIANCE']
const trades = [['BSE_10009501', '11:33:31 am', 'TCS', 'Motilal Oswal Financial', 'SELL', '175', '₹4205.50', '₹7,35,962.5'], ['BSE_10009502', '11:33:31 am', 'HDFCBANK', 'Zerodha Alpha Client', 'BUY', '200', '₹1646.00', '₹3,29,200'], ['BSE_10009503', '11:33:32 am', 'INFY', 'ICICI Prudential MF', 'BUY', '225', '₹1836.50', '₹4,13,212.5'], ['BSE_10009504', '11:33:32 am', 'ICICIBANK', 'Arham Capital PMS', 'SELL', '250', '₹1177.00', '₹2,94,250'], ['BSE_10009505', '11:33:32 am', 'SBIN', 'Kotak Institutional Equities', 'BUY', '275', '₹817.50', '₹2,24,812.5'], ['BSE_10009506', '11:33:33 am', 'TATAMOTORS', 'HDFC Securities Prop Desk', 'BUY', '300', '₹988.00', '₹2,96,400'], ['BSE_10009507', '11:33:33 am', 'BHARTIARTL', 'Motilal Oswal Financial', 'SELL', '325', '₹1468.50', '₹4,77,262.5'], ['BSE_10009508', '11:33:33 am', 'ITC', 'Zerodha Alpha Client', 'BUY', '350', '₹484.00', '₹1,69,400']]

function Tip({ children, text }: { children: React.ReactNode; text: string }) { return <Tooltip><TooltipTrigger asChild>{children}</TooltipTrigger><TooltipContent className="max-w-64">{text}</TooltipContent></Tooltip> }
function Panel({ title, subtitle, children, action }: { title: string; subtitle?: string; children: React.ReactNode; action?: React.ReactNode }) { return <Card className="panel overflow-hidden"><CardHeader className="flex flex-row items-start justify-between gap-3 pb-3"><div><CardTitle className="flex items-center gap-2 text-sm font-semibold tracking-tight"><GripVertical className="size-4 text-muted-foreground/40" />{title}<Tip text={subtitle || 'Live telemetry panel with contextual performance detail.'}><Info className="size-3.5 text-muted-foreground" /></Tip></CardTitle>{subtitle && <p className="mt-1 text-xs text-muted-foreground">{subtitle}</p>}</div>{action}</CardHeader><CardContent>{children}</CardContent></Card> }

export function FintechDashboard() {
  const [active, setActive] = useState('ALL'); const [live, setLive] = useState(true); const [range, setRange] = useState('15m'); const [query, setQuery] = useState(''); const [pulled, setPulled] = useState(false)
  const visibleTrades = useMemo(() => trades.filter((t) => (active === 'ALL' || t[2] === active) && t.join(' ').toLowerCase().includes(query.toLowerCase())), [active, query])
  return <TooltipProvider delayDuration={180}><main className="min-h-screen bg-background px-4 py-5 text-foreground md:px-7 lg:px-10">
    <header className="flex flex-col gap-5 border-b border-border/70 pb-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-start gap-3"><div className="mt-1 flex size-9 items-center justify-center rounded-xl bg-primary text-primary-foreground"><Activity className="size-5" /></div><div><div className="flex flex-wrap items-center gap-3"><h1 className="font-mono text-xl font-bold tracking-tight md:text-2xl">ARHAM FINTECH</h1><Badge variant="outline" className="border-primary/40 text-primary">BSE Real-Time Ingestion</Badge></div><p className="mt-1 text-xs text-muted-foreground md:text-sm">Resilient trade aggregator designed for 15-min BSE pulls & 30s connection timeout mitigation</p></div></div><div className="flex flex-wrap items-center gap-2"><Badge variant="outline" className="h-10 gap-2 border-border bg-card px-3 font-mono text-xs"><span className="size-2 rounded-full bg-primary shadow-[0_0_10px_var(--primary)]" />Status: <span className="text-primary">{pulled ? 'Pull Completed (10,000 trades)' : 'Streaming · 10,000 trades'}</span></Badge><Button onClick={() => setPulled(true)} className="h-10 gap-2"><RefreshCw className="size-4" />Trigger BSE Pull</Button></div></header>
    <div className="flex flex-col gap-3 py-5 lg:flex-row lg:items-center lg:justify-between"><Tabs value={range} onValueChange={setRange}><TabsList className="bg-card"><TabsTrigger value="5m">5m</TabsTrigger><TabsTrigger value="15m">15m</TabsTrigger><TabsTrigger value="1h">1h</TabsTrigger><TabsTrigger value="1d">1d</TabsTrigger></TabsList></Tabs><div className="flex items-center gap-2"><div className="relative"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><input aria-label="Search trades" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search trades..." className="h-9 w-52 rounded-md border border-input bg-card pl-9 pr-3 text-sm outline-none ring-primary focus:ring-2" /></div><Button variant="outline" size="sm" onClick={() => setLive(!live)} className="gap-2">{live ? <Pause className="size-3.5" /> : <Play className="size-3.5" />}{live ? 'Live' : 'Paused'}</Button><Button variant="outline" size="icon" aria-label="Dashboard settings"><Settings2 className="size-4" /></Button></div></div>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['Total Ingested Trades', '10,000', '+8.4%', 'vs previous pull'], ['Total Turnover', '₹3,82,16,31,875', '+12.6%', '₹42.8Cr / hour'], ['Active Equities', '10', '+2', 'symbols in stream'], ['Institutional Clients', '6', '100%', 'healthy connections']].map(([label, value, change, note], i) => <Card key={label} className="panel"><CardContent className="p-4"><p className="text-xs text-muted-foreground">{label}</p><div className="mt-2 flex items-end justify-between gap-2"><span className={`font-mono text-2xl font-bold ${i === 1 ? 'text-primary' : i === 2 ? 'text-chart-2' : i === 3 ? 'text-chart-3' : ''}`}>{value}</span><Badge variant="secondary" className="gap-1 text-primary"><ArrowUpRight className="size-3" />{change}</Badge></div><p className="mt-2 text-[11px] text-muted-foreground">{note}</p></CardContent></Card>)}</section>
    <section className="mt-3 grid gap-3 xl:grid-cols-3"><div className="xl:col-span-2"><Panel title="Turnover & trade flow" subtitle="₹ Crores · aggregated by 15-minute interval" action={<Button variant="ghost" size="icon" aria-label="Add panel"><Plus className="size-4" /></Button>}><ChartContainer config={{ turnover: { label: 'Turnover', color: 'var(--chart-1)' }, buys: { label: 'Buy flow', color: 'var(--chart-2)' } }} className="h-64 w-full"><AreaChart data={flow}><defs><linearGradient id="turnover" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="var(--color-turnover)" stopOpacity={0.35} /><stop offset="95%" stopColor="var(--color-turnover)" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--border)" /><XAxis dataKey="time" tickLine={false} axisLine={false} tick={{ fontSize: 10 }} /><YAxis tickLine={false} axisLine={false} tick={{ fontSize: 10 }} /><RechartsTooltip content={<ChartTooltipContent />} /><Area type="monotone" dataKey="value" name="turnover" stroke="var(--color-turnover)" fill="url(#turnover)" strokeWidth={2} /><Area type="monotone" dataKey="buys" name="buys" stroke="var(--color-buys)" fill="none" strokeDasharray="4 4" /></AreaChart></ChartContainer></Panel></div><Panel title="Ingestion health" subtitle="Current pull reliability"><div className="flex items-center gap-5"><ChartContainer config={{ healthy: { label: 'Healthy', color: 'var(--chart-1)' }, retry: { label: 'Retry', color: 'var(--chart-3)' } }} className="h-40 w-40"><PieChart><Pie data={[{ name: 'Healthy', value: 94 }, { name: 'Retry', value: 6 }]} dataKey="value" innerRadius={48} outerRadius={68} strokeWidth={3}><Cell fill="var(--color-healthy)" /><Cell fill="var(--color-retry)" /></Pie><RechartsTooltip content={<ChartTooltipContent />} /></PieChart></ChartContainer><div className="flex flex-col gap-3"><div><p className="font-mono text-2xl font-bold">99.94%</p><p className="text-xs text-muted-foreground">availability</p></div><div className="flex items-center gap-2 text-xs"><span className="size-2 rounded-full bg-primary" />Healthy <span className="text-muted-foreground">9,400</span></div><div className="flex items-center gap-2 text-xs"><span className="size-2 rounded-full bg-chart-3" />Retries <span className="text-muted-foreground">600</span></div></div></div><Separator className="my-4" /><div className="flex items-center justify-between text-xs"><span className="text-muted-foreground">Last successful pull</span><span className="font-mono text-primary">11:33:35 am</span></div></Panel></section>
    <section className="mt-3 grid gap-3 lg:grid-cols-2"><Panel title="Symbol distribution" subtitle="Trade count by equity"><ChartContainer config={{ trades: { label: 'Trades', color: 'var(--chart-2)' } }} className="h-48 w-full"><BarChart data={symbols.slice(1).map((s, i) => ({ symbol: s, trades: 360 - i * 27 }))}><CartesianGrid vertical={false} stroke="var(--border)" /><XAxis dataKey="symbol" tickLine={false} axisLine={false} tick={{ fontSize: 10 }} /><YAxis hide /><RechartsTooltip content={<ChartTooltipContent />} /><Bar dataKey="trades" name="trades" fill="var(--color-trades)" radius={[3, 3, 0, 0]} /></BarChart></ChartContainer></Panel><Panel title="API latency" subtitle="P50 and P95 response time · milliseconds"><ChartContainer config={{ p50: { label: 'P50', color: 'var(--chart-1)' }, p95: { label: 'P95', color: 'var(--chart-3)' } }} className="h-48 w-full"><LineChart data={latency}><CartesianGrid vertical={false} stroke="var(--border)" /><XAxis dataKey="name" tickLine={false} axisLine={false} tick={{ fontSize: 10 }} /><YAxis tickLine={false} axisLine={false} tick={{ fontSize: 10 }} /><RechartsTooltip content={<ChartTooltipContent />} /><Line type="monotone" dataKey="p50" stroke="var(--color-p50)" strokeWidth={2} dot={false} /><Line type="monotone" dataKey="p95" stroke="var(--color-p95)" strokeWidth={2} dot={false} strokeDasharray="5 4" /></LineChart></ChartContainer></Panel></section>
    <section className="mt-3"><Card className="panel overflow-hidden"><CardHeader className="flex flex-row items-center justify-between gap-3 border-b border-border/70 py-3"><CardTitle className="flex items-center gap-2 text-sm"><LayoutGrid className="size-4 text-primary" />Live trade stream <Badge variant="outline" className="ml-1 gap-1 text-[10px]"><span className="size-1.5 rounded-full bg-primary" />{visibleTrades.length} visible</Badge></CardTitle><div className="flex items-center gap-2"><Button variant="ghost" size="sm" className="gap-2"><SlidersHorizontal className="size-3.5" />Columns</Button><Button variant="ghost" size="icon" aria-label="Download trades"><Download className="size-4" /></Button></div></CardHeader><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-muted/40 font-mono text-[11px] uppercase tracking-wider text-muted-foreground"><tr>{['Trade ID', 'Timestamp', 'Symbol', 'Client', 'Type', 'Quantity', 'Price (₹)', 'Total Value (₹)'].map((h) => <th key={h} className="px-4 py-3 font-medium">{h}</th>)}</tr></thead><tbody>{visibleTrades.map((t, i) => <tr key={t[0]} className="border-t border-border/60 transition-colors hover:bg-muted/30"><td className="px-4 py-3 font-mono text-xs">{t[0]}</td><td className="px-4 py-3 font-mono text-xs text-muted-foreground">{t[1]}</td><td className="px-4 py-3"><Badge variant="outline" className="font-mono text-chart-2">{t[2]}</Badge></td><td className="px-4 py-3 text-xs">{t[3]}</td><td className="px-4 py-3"><Badge variant="outline" className={t[4] === 'BUY' ? 'border-primary/40 text-primary' : 'border-destructive/50 text-destructive'}>{t[4] === 'BUY' ? <ArrowUpRight className="mr-1 inline size-3" /> : <ArrowDownRight className="mr-1 inline size-3" />}{t[4]}</Badge></td><td className="px-4 py-3 text-right font-mono text-xs">{t[5]}</td><td className="px-4 py-3 text-right font-mono text-xs">{t[6]}</td><td className="px-4 py-3 text-right font-mono text-xs font-semibold text-primary">{t[7]}</td></tr>)}</tbody></table></div></Card></section>
    <footer className="flex flex-col gap-2 py-5 text-xs text-muted-foreground sm:flex-row sm:items-center sm:justify-between"><span className="flex items-center gap-2"><Zap className="size-3.5 text-primary" />Auto-refreshing every 30 seconds</span><span className="flex items-center gap-2"><Clock3 className="size-3.5" />Data window: {range} <Bell className="ml-2 size-3.5" /> 2 alerts</span></footer>
  </main></TooltipProvider>
}

export default FintechDashboard
